### ISSUE TITLE
Backup Preferences loaded

### ISSUE THREAD

**Issue by eduarcor** [Vinylwalk3r/JDownloader-2-Dark-Theme#1]
The look is AMAZING!! Congrats dude!! I love it.
But there is a problem, loading the backup, not just loads the colours but all the rest of the preferences, for example it points in several places a johannes directory (C:\Users\Johannes\Documents\GitHub\Jdownloader-2-Dark-Theme)...
And there are other several setting which are not the default for jdownloader, like menus and so on.
You could start just sharing what are the setting to change just the colours and sharing here. Unless there is a way to create a backup just for the colours, and not for the rest of it.
Should be great to be as agnostic as possible of anything, just changing the colours.
As the backup is binary, there is a problem trying to see what is happening underneath.
Please help us.
Thanks and greetings!! Great work!!

**Comment by Georgeto** [comment]
>  I think it is a must to find a way not touching anything but the colours...

I did exactly this in #2.

**Comment by eduarcor** [comment]
It does beautifully work!! Thanks.
The only last caviat is, that in MacOS at least the windows frame is still light gray...
Is there any way to solve it? Cheers!!
![captura de pantalla 2018-10-03 a las 2 46 42](https://user-images.githubusercontent.com/1464379/46384591-32e54080-c6b7-11e8-8df6-30e43a6e527c.png)

**Comment by SFNR1** [comment]
The Theme is quite nice, but you just exported ALL your Jdownloadersettings, even your PREMIUM-ACCOUNTS are in there!!! Delete that immediately!

**Comment by Vinylwalk3r** [comment]
Yeup, I forgot to work from a blank slate, not building upon my existing settings...thats what happens when sharing your work is a afterthought when your finished. My bad.
But I've redone the ENTIRE dang thing, top to bottom from scratch. No personal settings, nothing. Just the colors and some reorganized toolbars in the CustomToolbars version.


> The look is AMAZING!! Congrats dude!! I love it.
> But there is a problem, loading the backup, not just loads the colours but all the rest of the preferences, for example it points in several places a johannes directory (C:\Users\Johannes\Documents\GitHub\Jdownloader-2-Dark-Theme)...
> And there are other several setting which are not the default for jdownloader, like menus and so on.
> You could start just sharing what are the setting to change just the colours and sharing here. Unless there is a way to create a backup just for the colours, and not for the rest of it.
> Should be great to be as agnostic as possible of anything, just changing the colours.
> As the backup is binary, there is a problem trying to see what is happening underneath.
> Please help us.
> Thanks and greetings!! Great work!!

Yeah, a lot of good folks pointed it out for me. I'll be honest here, I COMPLTETLY forgot those settings were there when I uploaded. Used JD2 customized with those settings for so long, I took them for granted....My bad. But now the thing is Redone from scratch, so no settings except for the colors and themes. (the CustomToolbars verison has reorganized toolbars, added them as a bonus ^^) 
I never went below the "LAFSettings" in the Advanced Section of the Settings menus. So the binary stuff, I'll leave that for someone who can read it ;)

Georgeto made something interesting in the fork [here] (https://github.com/Vinylwalk3r/Jdownloader-2-Dark-Theme/pull/2)

**Comment by eduarcor** [comment]
Could you please add some screenshots of the new changes (the bars changes) and update the info in the help (it still says you will lose all your settings... when you apply)?
Thanks!!

**Comment by Vinylwalk3r** [comment]
There, think that does it. 
1. I dotn think its necessary to add new imgs, cause I keept the bars as is in the CustomToolbars file
and 2. hows the explanations above the step-by-steps guides now? One clears your settings, the other merges. Choose you poison, as they say ;)

**Comment by eduarcor** [comment]
So, the merging thing, without overriding any custom settings, is exactly the same of Georgeto's way...
No other important changes as the other options just overrides everything -which is a no go existing the other much better method without poluting anything-, even if you clean that up with other customizations you had...
So, I don't need to change anything and will keep Georgeto's files then. Thanks.

**Comment by Vinylwalk3r** [comment]
Exactly! Georgeto's procedure was perfect, so I incorporated it. May remove the other way entirely, but I'll keep the backup files in the repo.

**Comment by Vinylwalk3r** [comment]
> It does beautifully work!! Thanks.
> The only last caviat is, the windows frame is still light gray, in MacOS at least (in Dark mode in Mojave)...
> Is there any way to solve it? Cheers!!
> 
> ![captura de pantalla 2018-10-03 a las 2 46 42](https://user-images.githubusercontent.com/1464379/46384591-32e54080-c6b7-11e8-8df6-30e43a6e527c.png)
> 
> **Edit 1:** There is a way to do it, and makes everything black but doesn't respect the windows MacOS style, is another one (which I personally don't like too much).
> Just go to "LAFSettings: Window Decoration | (JD09 sytle)Paint the window title bar." and set it to true. I couldn't find any other way.
> 
> ![screenshot 2018-10-03 at 13 23 47](https://user-images.githubusercontent.com/1464379/46407547-9ac77580-c70f-11e8-9494-d02d47d5c82f.png)
> 
> **Edit 2:** I don't like personally that the progress bar are animated, with 2 colours in between, I tried to play with the 1 to 5 Color progress bar background, first eliminating and then putting the same colours, but it didn't work. Maybe you can help me with that. Thanks!!
> 
> ![screenshot 2018-10-03 at 13 22 23](https://user-images.githubusercontent.com/1464379/46407493-710e4e80-c70f-11e8-9ff4-fa9488be9ff3.png)
> 
> **Edit 3:** There are buttons, like the ones in the Bottom with just an small arrow, that are really small (it looks like when you change to the BLACK EYE theme it changes the theme style completely and the buttons are smaller and rounder... It should be great just to change the colours but not the Windows style in the interface. Is this a possibility (I like the default one, just not the colours). I mean, I know that this one could be really complicated. Just asking and trying to get better. The work is amazing, thanks!!
> 
> ![screenshot 2018-10-03 at 13 23 47 2](https://user-images.githubusercontent.com/1464379/46408195-97cd8480-c711-11e8-8a40-c9907069fb72.png)
> 
> **Edit 4:** After I updated (when it tells you that there is an update available), when it restarts the interface turns to the default one (light again)... (**edit: after the automatic restart, just close it, and then start it again, it will open with the dark interface, don't try to modify anything, is just at restart time, I think it loads the defaults, until you start it again normally...**)
> 
> **P.S.: By any chance, do you know something similar to qBittorrent? (Is the only one still bothers me in the UI)**

Howdy Dudy man, that is some work you laid down there! And for that, you get a cookie ^^ Naa, but I found a way for us to ditch the Candy Cane way and use our own! In the [customthemes] (https://github.com/Vinylwalk3r/JDownloader-2-Dark-Theme/tree/master/customthemes) folder, I included both an edited BlackEye.jar theme, and the .png files to create a green progress bar. I think it looks killer, if I may say so. 
Also, the buttons are that IMHO unusable design cause they dont have a icon or name set for their button, so only that teny tiny thingy is left....
As for why Mojave DARK THEME leaves a WHITE titlebar....idk but that titlebar you dug out is better than nothing....good work on that fellow digger! ;)
