### ISSUE TITLE
Dark Theme Pre-installed version

### ISSUE THREAD

**Issue by shojimeguro** [Vinylwalk3r/JDownloader-2-Dark-Theme#14]
i found some reference of pre-installed version : https://github.com/suratovvlad/qbittorrent-installer

is it possible to do this on jdownloader too?

**Comment by Vinylwalk3r** [comment]
If I understand you right, your asking if my theme cant be implemented into JD2 natively (ish)? Actually, Im talking to the devs about doing something just like this! Even though they dont have time right now to implement it, it's on the to-do list, so hopes are high!

**Comment by shojimeguro** [comment]
> If I understand you right, your asking if my theme cant be implemented into JD2 natively (ish)? Actually, Im talking to the devs about doing something just like this! Even though they dont have time right now to implement it, it's on the to-do list, so hopes are high!

yes or when i install jdownloader dark theme installer version then it will automatically implement theme so when i launch it already dark theme

**Comment by leeuniverse** [comment]
LOL...  That's funny.  They directly contact you to help make it part of JDownloader and whatever, to "fix it up", and then they just put it "on the list" of things to do.  LOL

**Comment by jiaz83** [comment]
See my comment, https://github.com/Vinylwalk3r/JDownloader-2-Dark-Theme/issues/13

**Comment by Vinylwalk3r** [comment]
> LOL... That's funny. They directly contact you to help make it part of JDownloader and whatever, to "fix it up", and then they just put it "on the list" of things to do. LOL

Weeeeell....They got their hands full as is and I've got a busy life. It's on our "We do it when we have the time / opportunity to" list....
