### ISSUE TITLE
Every time Jdownloader gets an update, it breaks the dark theme

### ISSUE THREAD

**Issue by TheArgentinian** [Vinylwalk3r/JDownloader-2-Dark-Theme#17]
I have to copy the cfg and themes folder each time.
![Sin título](https://user-images.githubusercontent.com/59894621/73175850-da2a8a00-40e9-11ea-86f6-3496f5b16fbf.png)

**Comment by allan-garrido** [comment]
me too

**Comment by Cupbox** [comment]
If you restart Jdownloader, it's back to normal.

**Comment by jiaz83** [comment]
This is a known issue and happens to every theme. We're working on it

**Comment by Vinylwalk3r** [comment]
> If you restart Jdownloader, it's back to normal.

Thats what I've always done ;)

**Comment by TheArgentinian** [comment]
> 
> 
> If you restart Jdownloader, it's back to normal.

JD restarts itself after updating. The interface turns almost white like in the image that I included!

**Comment by TheArgentinian** [comment]
> 
> 
> > If you restart Jdownloader, it's back to normal.
> 
> Thats what I've always done ;)

JD restarts itself after updating. The interface turns almost white like in the image that I included!

**Comment by Cupbox** [comment]
Yes and if you restart after that, it gets fixed.
