### ISSUE TITLE
Window bar doesn't turn dark

### ISSUE THREAD

**Issue by fwd079** [Vinylwalk3r/JDownloader-2-Dark-Theme#27]
Thanks, nice theme. Not sure if Windows or JD, but after dark theme installed, the window bar still remains on "default" theme.

![image](https://user-images.githubusercontent.com/7912632/99879309-0d538200-2c04-11eb-980c-34ba96864d3c.png)

Kind Regards.

**Comment by nero-0** [comment]
This is a Windows behavior, it has nothing to do with JD2.

Just fine here
![sddt1](https://user-images.githubusercontent.com/42862510/99895451-0f9af800-2c67-11eb-80c1-d18ab3cfd722.png)

You can change this through the Windows personalization settings.

**Comment by fwd079** [comment]
Oh okay, thanks. Closing.
