### ISSUE TITLE
Buttons uncomfortably glossy

### ISSUE THREAD

**Issue by ghost** [Vinylwalk3r/JDownloader-2-Dark-Theme#5]
Thank you so much for doing this. It's much easier on the eyes. One bit of feedback I have though is the buttons can be really glossy, especially when they are vertically 'short'

![](https://i.imgur.com/Kc9ZfjB.png)

Flatter buttons, or completely flat buttons, would be heavenly.

**Comment by Vinylwalk3r** [comment]
Hmm....I could look into that. Shouldn't be to difficult...

**Comment by Vinylwalk3r** [comment]
Before I go live, what do you think of this? Modding the theme is surprisingly easy ^^
![newbuttons](https://user-images.githubusercontent.com/35334790/52750610-0807e300-2fed-11e9-97ca-1e809692fff9.JPG)

**Comment by Aidolii** [comment]
Looks much better

**Comment by Vinylwalk3r** [comment]
I wonder if they should go live or not...

**Comment by Aidolii** [comment]
Put them in a separate branch and I'll try them out.

**Comment by blvz** [comment]
> I wonder if they should go live or not...
They really should.

**Comment by Vinylwalk3r** [comment]
I put the buttons in this branch. Test it, give feedback 'n we'll go live!
https://github.com/Vinylwalk3r/JDownloader-2-Dark-Theme/pull/10

**Comment by Aidolii** [comment]
There is only one button image in the beta branch. It does seem to be working though, for what it's worth.

**Comment by Vinylwalk3r** [comment]
> There is only one button image in the beta branch. It does seem to be working though, for what it's worth.

Thanx for pointing it out to me. I have no idea what happened, there should have been like seven images there.
But now I've fixed that and they're published in the master repo! Flat and Unglossy Buttons are out of beta and Live! (also changed a lot of icons from black to white so they're easier to see)
