### ISSUE TITLE
How do I get a title bar like that?

### ISSUE THREAD

**Issue by Aidolii** [Vinylwalk3r/JDownloader-2-Dark-Theme#6]
In this screenshot you have a title bar that doesn't match the rest of the screenshots.

![](https://github.com/Vinylwalk3r/Jdownloader-2-Dark-Theme/blob/master/images/SettingsTab.JPG?raw=true)

I tried enabling 'LAFSettings: Window Decoration' but that didn't give me the same titlebar, plus it puts an ugly white outline around the entire window. (Though honestly it's still better than the default one.)

![](https://i.imgur.com/Rwi5XQy.png)

**Comment by Vinylwalk3r** [comment]
It is actually really, I have the Windows color setting set to a Grey color ;)

**Comment by Aidolii** [comment]
Ah, I see, accent coloring the taskbar with a dark color. Neat.
